import { PhenotypeInfo } from "@/lib/types";

export const PHENOTYPES: PhenotypeInfo[] = [
  {
    code: "MHNW",
    full_name: "Metabolically Healthy Normal Weight",
    bmi_range: "BMI < 25",
    metabolic_status: "No metabolic risk factors",
    clinical_note: "Reference group. Maintain current lifestyle.",
    risk_level: "low",
    color: "green",
    percentage: 27.1,
  },
  {
    code: "MUNW",
    full_name: "Metabolically Unhealthy Normal Weight",
    bmi_range: "BMI < 25",
    metabolic_status: ">=3 metabolic risk factors",
    clinical_note: "Skinny fat phenotype. Normal BMI can hide metabolic risk.",
    risk_level: "moderate",
    color: "yellow",
    percentage: 1.2,
  },
  {
    code: "MHOW",
    full_name: "Metabolically Healthy Overweight",
    bmi_range: "25 <= BMI < 30",
    metabolic_status: "No metabolic risk factors",
    clinical_note: "Overweight paradox phenotype. Continue lifestyle follow-up.",
    risk_level: "low",
    color: "blue",
    percentage: 24.1,
  },
  {
    code: "MUOW",
    full_name: "Metabolically Unhealthy Overweight",
    bmi_range: "25 <= BMI < 30",
    metabolic_status: ">=3 metabolic risk factors",
    clinical_note: "Pre-obesity risk group and key early intervention target.",
    risk_level: "moderate",
    color: "orange",
    percentage: 6.6,
  },
  {
    code: "MHO",
    full_name: "Metabolically Healthy Obese",
    bmi_range: "BMI >= 30",
    metabolic_status: "No metabolic risk factors",
    clinical_note: "Obesity paradox phenotype. Monitor carefully over time.",
    risk_level: "low",
    color: "violet",
    percentage: 21.6,
  },
  {
    code: "MUO",
    full_name: "Metabolically Unhealthy Obese",
    bmi_range: "BMI >= 30",
    metabolic_status: ">=3 metabolic risk factors",
    clinical_note: "Classic high-risk phenotype requiring intensive intervention.",
    risk_level: "high",
    color: "red",
    percentage: 19.3,
  },
];

export const FIELD_LABELS: Record<string, { label: string; unit: string; hint?: string }> = {
  bmi: { label: "BMI", unit: "kg/m2", hint: "Body Mass Index" },
  waist_cm: { label: "Waist Circumference", unit: "cm" },
  hip_cm: { label: "Hip Circumference", unit: "cm" },
  height_cm: { label: "Height", unit: "cm" },
  weight_kg: { label: "Weight", unit: "kg" },
  systolic_bp: { label: "Systolic Blood Pressure", unit: "mmHg" },
  diastolic_bp: { label: "Diastolic Blood Pressure", unit: "mmHg" },
  fasting_glucose: { label: "Fasting Glucose", unit: "mg/dL" },
  hdl: { label: "HDL Cholesterol", unit: "mg/dL", hint: "Good cholesterol" },
  triglycerides: { label: "Triglycerides", unit: "mg/dL" },
  serum_insulin: { label: "Fasting Insulin", unit: "uU/mL" },
  hba1c: { label: "HbA1c", unit: "%", hint: "Glycated hemoglobin" },
  hs_crp: { label: "hs-CRP", unit: "mg/L", hint: "Inflammation marker" },
  age: { label: "Age", unit: "years" },
  income_poverty_ratio: { label: "Income-to-Poverty Ratio", unit: "0-5" },
  sedentary_minutes: { label: "Sedentary Time", unit: "min/day" },
};
